# This is a basic workflow to help you get started with Actions

name: Build_Push_Agent

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: 'Login via Azure CLI'
        uses:  azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username:     ${{ secrets.REGISTRY_USERNAME }}
          password:     ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t  ${{ vars.REGISTRY_LOGIN_SERVER }}/agentrunner:${{ github.run_number }} .
          docker tag  ${{ vars.REGISTRY_LOGIN_SERVER }}/agentrunner:${{ github.run_number }}  ${{ vars.REGISTRY_LOGIN_SERVER }}/agentrunner:latest
          docker push  ${{ vars.REGISTRY_LOGIN_SERVER }}/agentrunner:${{ github.run_number }} && docker push  ${{ vars.REGISTRY_LOGIN_SERVER }}/agentrunner:latest

      - name: Create Helm chart
        run: |
          cd ./ghrhelm
          helm package .
          
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          
      - name: Deploy via Helm
        run: |
          cd ./ghrhelm
          helm install agentrunner -n agentrunnerpool ghr-0.0.1.tgz \
            --set image.repository=gitacrwest001.azurecr.io/agentrunner \
            --set image.tag=latest \
            --set ghr.github_token=${{ secrets.TOKEN }} \
            --set ghr.repo_owner=ZundereneWork \
       
