# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on: push

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses:  azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Create Helm chart
          run: |
            # az configure --defaults acr=${CLUSTER_NAME}
            # az acr login -n ${CLUSTER_NAME}
            cd ./ghrhelm
            helm package .
            # helm push ghr-0.0.1.tgz oci://${CLUSTER_NAME}.azurecr.io/ghrunner
        - name: AKS set context
          uses: azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}
            
        - name: Deploy via Helm
          run: |
            cd ./ghrhelm
            # az configure --defaults acr=${CLUSTER_NAME}
            # helm pull oci://gitacrwest001.azurecr.io/ghrunner/ghr --version 0.0.1
            helm install agentrunner ghr-0.0.1.tgz \
              --set image.repository=gitacrwest001.azurecr.io/agent \
              --set image.tag=latest \
              --set ghr.github_token=${{ secrets.TOKEN }} \
              --set ghr.repo_owner=ZundereneWork \

      
