# This is a basic workflow to help you get started with Actions

name: Build_Push_Agent

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: 'Login via Azure CLI'
        uses:  azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username:     ${{ secrets.REGISTRY_USERNAME }}
          password:     ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t  ${{ vars.REGISTRY_LOGIN_SERVER }}/agent:latest
          docker build . -t  ${{ vars.REGISTRY_LOGIN_SERVER }}/agent:${{ github.run_number }}
          docker push  ${{ vars.REGISTRY_LOGIN_SERVER}}/agent:latest
          docker push  ${{ vars.REGISTRY_LOGIN_SERVER }}/agent:${{ github.run_number }}
  