# This is a basic workflow to help you get started with Actions

name: Build_Push_Agent

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: 'Login via Azure CLI'
        uses:  azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Helm chart
        run: |
          cd ./ghrhelm
          helm package .
          
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          
      - name: Deploy via Helm
        run: |
          cd ./ghrhelm
          if ( $($(helm list -n agentrunnerpool) | Select-Object -Last 1 | measure).Count -ne 0 ) {
             helm upgrade agentrunner hr-0.0.1.tgz -n agentrunnerpool g \
              --set image.repository=gitacrwest001.azurecr.io/agentrunner \
              --set image.tag=latest \
              --set ghr.github_token=${{ secrets.TOKEN }} \
              --set ghr.repo_owner=ZundereneWork \
          } else {
            helm install agentrunner  ghr-0.0.1.tgz -n agentrunnerpool \
              --set image.repository=gitacrwest001.azurecr.io/agentrunner \
              --set image.tag=latest \
              --set ghr.github_token=${{ secrets.TOKEN }} \
              --set ghr.repo_owner=ZundereneWork \
          }
        shell: pwsh
          
       
