#
name: prometeus

# Controls when the workflow will run
on: [workflow_dispatch]

jobs:
  deploymenPrometheus:
    runs-on: AgentRunnerZun
    steps:
      - name: 'Add Prometheus'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus -n prometheus prometheus-community/prometheus